### ISSUE TITLE
correct if you typed the wrong css in the header

### ISSUE THREAD

**Issue by developerZok** [farrukhmusratov/Kun.uz#1]
correct if you typed the wrong css in the header
![Screenshot from 2021-10-25 12-47-45](https://user-images.githubusercontent.com/91331822/138655915-64e96d57-a3f5-4c6b-a579-b6783750b0bc.png)

**Comment by developerZok** [comment]
Your mistake was in line 17

**Comment by farrukhmusratov** [comment]
raxmat sizga oqkongil inson
